package:
  name: tradetide
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../
  git_url: https://github.com/MartinPdeS/TradeTide.git

build:
  number: 0
  script:
    - export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

channels:
  - conda-forge
  - martinpdes

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python {{ PY_VER }}*
    - scikit-build-core ~=0.3
    - pybind11 ~=2.13
    - python-build ~=1.2
    - setuptools_scm[toml] ~=8.0
    - numpy ==2.2.6
  run:
    - pandas ~=2.3.0
    - martinpdes::mpsplots
    - matplotlib ~=3.8
    - numpy ==2.2.6
    - pydantic ~=2.9


about:
  home: https://github.com/MartinPdeS/TradeTide
  license: MIT
  summary: "A package Forex stocks backtesting."
  description: The library is a tool for strategies testing for the Forex current exchange market.
  dev_url: https://github.com/MartinPdeS/TradeTide
  doc_url: https://martinpdes.github.io/TradeTide/
  license_file: LICENSE
  keywords:
    - optics
    - refractive index
    - material

test:
  imports:
    - TradeTide
  requires:
    - python {{ PY_VER }}*
    - pytest>=0.6
    - pytest-cov>=2.0
    - pytest-json-report==1.5.0
    - coverage==7.6.1
  commands:
    - python -m pytest
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS
