# file generated by vcs-versioning
# don't change, don't track in version control
__all__ = ["__version__", "__version_tuple__", "version", "version_tuple", "__commit_id__", "commit_id"]

__version__ = version = '0.2.7'
__version_tuple__ = version_tuple = (0, 2, 7)
__commit_id__ = commit_id = 'gf04982c68'
