# file generated by vcs-versioning
# don't change, don't track in version control
__all__ = ["__version__", "__version_tuple__", "version", "version_tuple", "__commit_id__", "commit_id"]

__version__ = version = '1.0.0'
__version_tuple__ = version_tuple = (1, 0, 0)
__commit_id__ = commit_id = None
