#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/chrono.h>
#include <pybind11/numpy.h>
#include "market/market.h"

namespace py = pybind11;
enum class OrderSide { Buy, Sell };
enum class OrderType { Market, Limit, Stop, StopLimit };
enum class OrderStatus { Pending, Filled, Cancelled, Expired };
struct Order { std::string order_id; OrderSide side; OrderType order_type; TimePoint submitted_at; std::optional<double> limit_price, stop_price; std::optional<TimePoint> expires_at; OrderStatus status=OrderStatus::Pending; bool stop_triggered=false;
    Order(std::string id, OrderSide s, OrderType t, TimePoint at, std::optional<double> limit={}, std::optional<double> stop={}, std::optional<TimePoint> expires={}):order_id(std::move(id)),side(s),order_type(t),submitted_at(at),limit_price(limit),stop_price(stop),expires_at(expires) {
        if ((t==OrderType::Limit&&!limit)||(t==OrderType::Stop&&!stop)||(t==OrderType::StopLimit&&(!limit||!stop))) throw std::invalid_argument("Order type requires its configured price.");
        if ((limit&&*limit<=0)||(stop&&*stop<=0)) throw std::invalid_argument("Order prices must be positive.");
        if (expires&&*expires<at) throw std::invalid_argument("expires_at cannot be before submitted_at."); }
};
struct OrderFill { std::string order_id; OrderSide side; OrderType order_type; TimePoint time; size_t index; double price; };
struct OrderBook { std::vector<Order> orders; std::vector<OrderFill> fills; OrderBook(std::vector<Order> value={}):orders(std::move(value)){}
    Order& place(Order order) { for(auto& existing:orders) if(existing.order_id==order.order_id) throw std::invalid_argument("Duplicate order_id."); orders.push_back(std::move(order)); return orders.back(); }
    void cancel(const std::string& id) { for(auto& order:orders) if(order.order_id==id) { if(order.status==OrderStatus::Pending) order.status=OrderStatus::Cancelled; return; } throw std::out_of_range("Unknown order_id."); }
    std::optional<double> price(Order& order,const Market& market,size_t i) { const auto& p=order.side==OrderSide::Buy?market.ask:market.bid; double open=p.open[i],low=p.low[i],high=p.high[i]; if(order.order_type==OrderType::Market)return open; if(order.order_type==OrderType::Limit||(order.order_type==OrderType::StopLimit&&order.stop_triggered)){ bool hit=order.side==OrderSide::Buy?low<=*order.limit_price:high>=*order.limit_price; if(!hit)return {}; return order.side==OrderSide::Buy?std::min(open,*order.limit_price):std::max(open,*order.limit_price); } bool hit=order.side==OrderSide::Buy?high>=*order.stop_price:low<=*order.stop_price; if(!hit)return {}; if(order.order_type==OrderType::StopLimit){order.stop_triggered=true;return price(order,market,i);} return order.side==OrderSide::Buy?std::max(open,*order.stop_price):std::min(open,*order.stop_price); }
    std::vector<OrderFill> process(const Market& market) { for(size_t i=0;i<market.dates.size();++i) for(auto& order:orders) { auto time=market.dates[i]; if(order.status!=OrderStatus::Pending||time<order.submitted_at)continue; if(order.expires_at&&time>*order.expires_at){order.status=OrderStatus::Expired;continue;} auto value=price(order,market,i); if(value){order.status=OrderStatus::Filled;fills.push_back({order.order_id,order.side,order.order_type,time,i,*value});}} return fills; }
    std::vector<int> trade_signals(const Market& market) { process(market); std::vector<int> result(market.dates.size()); for(const auto& fill:fills) result[fill.index]=fill.side==OrderSide::Buy?1:-1; return result; }
};
PYBIND11_MODULE(orders,m){ py::enum_<OrderSide>(m,"OrderSide").value("BUY",OrderSide::Buy).value("SELL",OrderSide::Sell); py::enum_<OrderType>(m,"OrderType").value("MARKET",OrderType::Market).value("LIMIT",OrderType::Limit).value("STOP",OrderType::Stop).value("STOP_LIMIT",OrderType::StopLimit); py::enum_<OrderStatus>(m,"OrderStatus").value("PENDING",OrderStatus::Pending).value("FILLED",OrderStatus::Filled).value("CANCELLED",OrderStatus::Cancelled).value("EXPIRED",OrderStatus::Expired); py::class_<Order>(m,"Order").def(py::init<std::string,OrderSide,OrderType,TimePoint,std::optional<double>,std::optional<double>,std::optional<TimePoint>>(),py::arg("order_id"),py::arg("side"),py::arg("order_type"),py::arg("submitted_at"),py::arg("limit_price")=py::none(),py::arg("stop_price")=py::none(),py::arg("expires_at")=py::none()).def_readonly("order_id",&Order::order_id).def_readwrite("status",&Order::status); py::class_<OrderFill>(m,"OrderFill").def_readonly("order_id",&OrderFill::order_id).def_readonly("side",&OrderFill::side).def_readonly("order_type",&OrderFill::order_type).def_readonly("time",&OrderFill::time).def_readonly("index",&OrderFill::index).def_readonly("price",&OrderFill::price); py::class_<OrderBook>(m,"OrderBook").def(py::init<std::vector<Order>>(),py::arg("orders")=std::vector<Order>{}).def_readwrite("orders",&OrderBook::orders).def_readwrite("fills",&OrderBook::fills).def("place",&OrderBook::place,py::return_value_policy::reference_internal).def("cancel",&OrderBook::cancel).def("process",&OrderBook::process).def("trade_signals",[](OrderBook& book,const Market& market){ const auto signals=book.trade_signals(market); py::array_t<int> result(signals.size()); auto output=result.mutable_unchecked<1>(); for(size_t i=0;i<signals.size();++i) output(i)=signals[i]; return result; }); }
